import type { CustomizeControl } from "../../../customize";
import { select, slider } from "../../controls";
import { fmt1, fmt2, fmtCount, fmtPct, fmtX } from "../../format";

export const customize: CustomizeControl[] = [
  select(
    "effect",
    "Effect",
    [
      { value: "spiral", label: "Spiral" },
      { value: "ripple", label: "Ripple" },
      { value: "vortex", label: "Vortex" },
      { value: "pulse", label: "Pulse" },
    ],
    "ripple",
  ),
  slider("shape", "Shape", {
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: 0.85,
    format: (n) => (n < 0.34 ? "Circle" : n < 0.67 ? "Squircle" : "Square"),
  }),
  slider("shapeShift", "Shape shift", {
    min: 0,
    max: 2,
    step: 0.05,
    defaultValue: 1,
    format: fmt2,
  }),
  slider("fillRatio", "Fill ratio", {
    min: 0.2,
    max: 1,
    step: 0.05,
    defaultValue: 0.6,
    format: fmtPct,
  }),
  slider("columns", "Columns", {
    min: 10,
    max: 80,
    step: 1,
    defaultValue: 59,
    format: fmtCount,
  }),
  slider("rows", "Rows", {
    min: 8,
    max: 56,
    step: 1,
    defaultValue: 32,
    format: fmtCount,
  }),
  slider("speed", "Speed", {
    min: 0,
    max: 3,
    step: 0.05,
    defaultValue: 1,
    format: fmtX,
  }),
  slider("waveFrequency", "Wave frequency", {
    min: 0.3,
    max: 4,
    step: 0.1,
    defaultValue: 4,
    format: fmt1,
  }),
  slider("wavePower", "Wave power", {
    min: 1,
    max: 10,
    step: 0.5,
    defaultValue: 7,
    format: fmt1,
  }),
  slider("spiralArms", "Arms", {
    min: 0,
    max: 12,
    step: 1,
    defaultValue: 11,
    format: fmtCount,
  }),
  slider("falloff", "Falloff", {
    min: 0.3,
    max: 4,
    step: 0.1,
    defaultValue: 1.8,
    format: fmt1,
  }),
  slider("baseAlpha", "Base alpha", {
    min: 0,
    max: 0.3,
    step: 0.01,
    defaultValue: 0.18,
    format: fmtPct,
  }),
  slider("colorSpeed", "Color cycle", {
    min: 0,
    max: 4,
    step: 0.1,
    defaultValue: 3.1,
    format: fmt1,
  }),
  slider("opacity", "Opacity", {
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: 1,
    format: fmtPct,
  }),
  select(
    "color1",
    "Color 1",
    [
      { value: "#7c3aed", label: "Violet" },
      { value: "#0a4d6b", label: "Teal" },
      { value: "#7a1f3d", label: "Burgundy" },
      { value: "#d4d4d4", label: "Silver" },
      { value: "#1e8a3a", label: "Forest" },
      { value: "#003566", label: "Navy" },
    ],
    "#7a1f3d",
  ),
  select(
    "color2",
    "Color 2",
    [
      { value: "#f0abfc", label: "Pink" },
      { value: "#22d3ee", label: "Cyan" },
      { value: "#fcd34d", label: "Amber" },
      { value: "#de7343", label: "Ember" },
      { value: "#93229D", label: "Magenta" },
      { value: "#ffffff", label: "White" },
    ],
    "#93229D",
  ),
];
