import type { CustomizeControl } from "../../../customize";
import { select, slider } from "../../controls";
import { fmt1, fmt2, fmtCount, fmtPct } from "../../format";

export const customize: CustomizeControl[] = [
  slider("columns", "Columns", {
    min: 8,
    max: 96,
    step: 1,
    defaultValue: 32,
    format: fmtCount,
  }),
  slider("depthRows", "Depth rows", {
    min: 10,
    max: 48,
    step: 1,
    defaultValue: 22,
    format: fmtCount,
  }),
  slider("fontScale", "Font scale", {
    min: 0.3,
    max: 1.2,
    step: 0.05,
    defaultValue: 0.9,
    format: fmt2,
  }),
  slider("scrollSpeed", "Scroll speed", {
    min: 0,
    max: 4,
    step: 0.1,
    defaultValue: 1,
    format: fmt1,
  }),
  slider("waveSpeed", "Wave speed", {
    min: 0,
    max: 3,
    step: 0.1,
    defaultValue: 1,
    format: fmt1,
  }),
  slider("wavePower", "Wave power", {
    min: 1,
    max: 12,
    step: 0.5,
    defaultValue: 6,
    format: fmt1,
  }),
  slider("waveFrequency", "Wave count", {
    min: 1,
    max: 8,
    step: 0.5,
    defaultValue: 3,
    format: fmt1,
  }),
  slider("waveAmplitude", "Wobble", {
    min: 0,
    max: 4,
    step: 0.1,
    defaultValue: 1.4,
    format: fmt1,
  }),
  slider("baseAlpha", "Base alpha", {
    min: 0,
    max: 0.3,
    step: 0.01,
    defaultValue: 0.07,
    format: fmtPct,
  }),
  slider("colorSpeed", "Color cycle", {
    min: 0,
    max: 4,
    step: 0.1,
    defaultValue: 1,
    format: fmt1,
  }),
  slider("opacity", "Opacity", {
    min: 0,
    max: 1,
    step: 0.05,
    defaultValue: 1,
    format: fmtPct,
  }),
  select(
    "color1",
    "Color 1",
    [
      { value: "#290596", label: "Indigo" },
      { value: "#0a4d6b", label: "Teal" },
      { value: "#7a1f3d", label: "Burgundy" },
      { value: "#d4d4d4", label: "Silver" },
      { value: "#1e8a3a", label: "Forest" },
      { value: "#003566", label: "Navy" },
    ],
    "#290596",
  ),
  select(
    "color2",
    "Color 2",
    [
      { value: "#93229D", label: "Magenta" },
      { value: "#f0abfc", label: "Pink" },
      { value: "#67e8f9", label: "Cyan" },
      { value: "#fcd34d", label: "Amber" },
      { value: "#de7343", label: "Ember" },
      { value: "#ffffff", label: "White" },
    ],
    "#93229D",
  ),
  select(
    "characters",
    "Charset",
    [
      { value: "0123456789ABCDEF", label: "Hex" },
      { value: "01", label: "Binary" },
      { value: "✶✤↣⌧✷*.;:", label: "Glyph" },
      { value: ".:-=+*#%@", label: "Density" },
      { value: "⌧✶✷✤☉ϟ", label: "Stars" },
    ],
    "0123456789ABCDEF",
  ),
];
